# Loading the required libraries

In [86]:
import pandas as pd 
import numpy as np
import spacy
from spacy import displacy
import networkx as nx
import os
import matplotlib.pyplot as plt
import scipy
import re
import nltk
import re
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
from collections import Counter
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mallika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mallika\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Mallika\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

# Loading the page that we scraped in the previous exercise

In [2]:
with open('webpage_source.txt', 'r', errors='ignore') as file: 
   data = file.read().replace( '\n', ' ')

In [46]:
data[0:2000]

'Jump to content Main menu Search Donate Create account Log in Toggle the table of contents Key events of the 20th century 2 languages Article Talk Read Edit View history Tools From Wikipedia, the free encyclopedia The 20th century changed the world in unprecedented ways. The World Wars sparked tension between countries and led to the creation of atomic bombs, the Cold War led to the space race and the creation of space-based rockets, and the World Wide Web was created. These advancements have played a significant role in citizens\' lives and shaped the 21st century into what it is today. Historic events in the 20th century[edit] World at the beginning of the century[edit] Main article: Edwardian era Map of colonial and land-based empires throughout the world in 1914 The new beginning of the 20th century marked significant changes. The 1900s saw the decade herald a series of inventions, including the automobile, airplane and radio broadcasting. 1914 saw the completion of the Panama Canal. The scramble for Africa continued in the 1900s and resulted in wars and genocide across the continent. The atrocities in the Congo Free State shocked the civilized world. From 1914 to 1918 the First World War, and its aftermath, caused major changes in the power balance of the world, destroying or transforming some of the most powerful empires. "The war to end all wars": World War I (1914â€“1918)[edit] Main article: World War I Arrest of a suspect in Sarajevo following the Assassination of Archduke Franz Ferdinand The First World War (or simply WWI), termed "The Great War" by contemporaries, started in July 1914 and ended in November 1918. The war was precipitated by the Assassination in Sarajevo of the Austro-Hungarian Empire\'s heir to the throne, Erzherzog Franz Ferdinand, by Gavrilo Princip, a member of the Young Bosnia liberation movement. After a period of diplomatic and military escalation known as the July Crisis, by the end of July 1914 two coalitions were at war: the Allies,'

# Evaluating the text

In [41]:
from nltk.tokenize import word_tokenize
tokenized_word = word_tokenize(data)
#print(tokenized_word)

In [69]:
from nltk.probability import FreqDist
dist_words = FreqDist(tokenized_word)
print(dist_words)

<FreqDist with 4838 samples and 22336 outcomes>

In [71]:
type(dist_words)

nltk.probability.FreqDist

In [74]:
pd.options.display.max_rows = None

In [79]:
df = pd.DataFrame(list(dist_words.items()), columns=['word', 'frequency'])

In [83]:
df.sort_values(by = 'frequency', ascending = False).head(1000)

                           word  frequency
39                            .       1642
12                          the       1134
31                            ,        980
14                           of        620
46                          and        412
1                            to        327
34                          The        320
79                            [        309
81                            ]        309
10                           in        307
144                          ''        275
3331                          ^        274
140                          ``        271
149                           )        255
146                           (        255
3333                       2018        253
1343                   December        231
3340                  Retrieved        209
65                            a        191
85                            :        177
59                          was        137
305                          on        131
52                          War        121
148                           “         98
188                          as         92
162                          by         79
141                         war         77
40                        World         76
171                          's         75
243                        from         71
218                        with         64
192                        were         64
112                         for         61
295                        that         58
507                          20         57
497                      Soviet         56
424                       which         55
694                      Hitler         51
383                          12         49
75                           it         47
283                         had         45
2106                         â€         43
2156                    History         43
403                          13         42
82                           at         42
219                     Germany         41
277                       first         40
3436                       ISBN         40
361                          11         39
128                         its         38
36                        world         38
422                          15         35
296                       would         35
19                      century         35
80                         edit         34
1351                      Japan         33
838                   September         32
205                          In         32
267                     Germans         32
1339                   Japanese         31
498                       Union         31
467                          II         31
733                      United         31
202                      German         31
375                         New         31
846                         but         30
3536                       ISSN         30
199                           ;         30
827                      August         30
364                      Europe         29
911                          an         29
518                      became         29
3383                          |         28
165                        July         28
235                        also         28
263                       their         27
468                         his         27
650                          27         26
2157                    nuclear         26
453                          18         26
341                         not         26
734                      States         25
1011                       June         25
291                          be         25
211                       after         25
449                        this         25
1093                     Battle         25
621                        This         24
730                        only         24
3570                   Archived         24
1244                          A         24
3571                   original         24
944                       April         24
113                      Africa         23
142                         end         23
912                      attack         23
94                          new         23
1227                    weapons         23
1373                    October         23
210                     against         23
73                         into         23
254                    American         22
968                         May         22
813                        1945         22
333                      during         22
490                      Stalin         21
135                          or         21
3400                        BBC         21
417                          17         21
808                   Holocaust         21
1277                      North         20
3527                       2017         20
505                         one         20
3                          Main         20
830                     Britain         20
18                         20th         20
315                        over         20
398                       other         19
193                      Allies         19
196                     British         19
3360                    January         19
474                        many         19
290                       could         18
276                           7         18
138                        most         18
3474                         p.         18
665                        Nazi         18
242                      forces         18
250                      Allied         18
190                         two         17
480                     However         17
967                          On         17
27                      history         17
677                        Jews         17
197                      France         17
853                       later         17
3540                          &         17
143                         all         17
1507                       U.S.         17
289                        they         17
45                    countries         17
1149                     Berlin         16
231                       South         16
529                      people         16
1230                       been         16
44                      between         16
20                            2         16
423                          16         16
1593                   February         16
51                         Cold         16
609                        such         16
2835                   Internet         15
3371                        How         15
167                    November         15
3368                       2016         15
29                         From         15
3342                          ?         15
3687                       York         15
2838                   computer         15
1105                   invasion         15
3588                       2014         15
204                           1         15
69                            '         15
47                          led         15
3473                      Press         15
273                           6         14
680                       Italy         14
76                           is         14
2421                    Vietnam         14
260                     nations         14
271                           5         14
84                      article         14
3379                   National         14
451                        made         14
1054                       1944         14
452                        more         14
161                       Great         14
3507                       2011         14
1069                     battle         14
918                        Army         14
1056                      about         13
340                         did         13
789                       under         13
834                      Poland         13
3573                       2009         13
355                  government         13
891                      Second         13
278                        used         13
937                        1940         13
132                       power         13
751                       began         13
127                       First         13
1698                      March         13
280                           8         13
1058                   Atlantic         13
1665                    Pacific         13
587                        time         13
182                       After         13
285                         out         13
1221                       1942         13
187                       known         13
53                        space         12
2723                      Space         12
421                          14         12
255                      troops         12
910                    launched         12
239                           3         12
63                         have         12
3467                 University         12
552                          23         12
389                     Nations         12
1108                  Operation         12
309                        came         12
3741                       2015         12
513                          21         12
348                          10         12
137                        some         12
611                          26         11
546                    economic         11
464                    Imperial         11
872                         use         11
336                       these         11
536                        when         11
1381                         By         11
2651                    Richard         11
582                          29         11
3484                       2012         11
1349                         US         11
311                           9         11
528                          he         11
617                       early         11
74                         what         11
126                        1918         11
855                        East         11
1103                         up         11
3378                    HISTORY         11
145                           I         11
2153                    Nuclear         11
131                       major         11
1026                     French         11
852                        days         10
1216                    several         10
1094                        now         10
1386                  Churchill         10
185                    military         10
2173                    Project         10
103                   including         10
306                        both         10
1573                       West         10
877                        army         10
1836                     island         10
116                        wars         10
3384                        Why         10
2784              International         10
3577                   Guardian         10
234                          It         10
2706                       John         10
170                      Empire         10
3578                  0261-3077         10
2039                      camps         10
884                         air          9
1222                    largest          9
604                          25          9
1142                       bomb          9
534                     Western          9
2280                      Korea          9
3610                       News          9
1111                     launch          9
327                        them          9
319                        next          9
717                          30          9
825                        Pact          9
1023                      where          9
547                      crisis          9
479                          19          9
481                    European          9
1786                  surrender          9
207                      Russia          9
427                       human          9
649                       state          9
256                           4          9
237                independence          9
1852                      India          9
419                     million          9
684                          28          9
682                   Mussolini          9
1684                      China          9
216                      Treaty          9
323                      forced          8
48                     creation          8
1084                      Nazis          8
1458                      naval          8
489                      Joseph          8
1401                       last          8
886                        part          8
2832                   Computer          8
883                     attacks          8
2578                     Korean          8
3447                    Journal          8
122                        Free          8
321                       years          8
1518                     second          8
3688                      Times          8
471                   communist          8
1109                        Sea          8
1613                  influence          8
443                     already          8
439                     leading          8
898                   territory          8
1005                       With          8
3665                        Was          8
286                    aircraft          8
287                         see          8
2983                 Foundation          8
1263                       city          8
3352                    Museums          8
533                       force          8
709                     Eastern          8
1661                     powers          8
227                      states          8
889                         any          8
1071                independent          7
760                          He          7
1654                        Day          7
3758                        And          7
3567                       Rise          7
1679                    Chinese          7
1076                     almost          7
3729                 Publishing          7
1586                     People          7
397                       among          7
1095                     turned          7
457                   communism          7
2529                        SSR          7
931                        1941          7
901                        USSR          7
3591                   Interest          7
372                      groups          7
1276                  offensive          7
1238                    despite          7
317                         set          7
631                        than          7
251                     advance          7
687                       large          7
2934                         PC          7
200                     Central          7
576                     general          7
32                         free          7
302                        form          7
697                        took          7
2369                    Michael          7
3644                       2008          7
3423                       PMID          7
2256                  computers          7
35                      changed          7
72                         21st          7
292                     warfare          7
953                 surrendered          7
3433                         pp          7
41                         Wars          7
3659                      S2CID          7
1288                     Rommel          7
1010                      being          7
530                          22          7
2180                     Robert          7
1788                  MacArthur          7
541                  Depression          7
3443                       What          7
543                      system          7
4045                       2013          7
83                    beginning          7
1233                    network          6
802                        held          6
790                     General          6
1319                        6th          6
2947                   software          6
612                        They          6
3312                       Year          6
3258                       2000          6
1073                         At          6
1649                    another          6
666                    soldiers          6
1374                       1943          6
660                        rise          6
969                     massive          6
1249                        day          6
744                        east          6
1208                   campaign          6
1454                      place          6
1114                   suffered          6
521                        rule          6
516                        even          6
542                  capitalist          6
510                        plan          6
506                     country          6
764                        area          6
548                 development          6
946                   important          6
766                  Conference          6
1009                      Paris          6
1167                     weapon          6
4260                    Century          6
933                      defeat          6
2929                        IBM          6
488                         few          6
566                    articles          6
826                      Moscow          6
3028                   networks          6
1429                       half          6
3553                       2003          6
585                   political          6
712                  population          6
1117                       turn          6
588                          24          6
1199                    planned          6
1038                        Air          6
456                  Revolution          6
3634                       2010          6
350                    occupied          6
1851                       Asia          6
60                      created          6
1717                    further          6
388                      League          6
54                         race          6
367                        upon          6
189                      Crisis          6
2028              concentration          6
166                       ended          6
114                   continued          6
373                         own          6
2438                    African          6
4033                   Research          6
2244                    systems          6
334                        Many          6
4081                     Atomic          6
139                    powerful          6
3689                  0362-4331          6
2355                      peace          6
2413                       1946          6
2158                     During          6
2284                      1980s          6
198                     Russian          6
1385                    victory          5
3870                   Heritage          5
596                      become          5
130                      caused          5
525                        well          5
339                     because          5
3380                   Archives          5
1077                    managed          5
1781                    Islands          5
1082                   Italians          5
1487                   possible          5
123                       State          5
1768                Philippines          5
1378                  victories          5
793                       Civil          5
799                     control          5
2580                    Missile          5
2579                      Cuban          5
288                          if          5
3733                     Museum          5
1524                      still          5
2433                    decades          5

### Observation : Exploring the text data shows it does have punctuation. The country names appear to be matching what is there in the countiries file that was provided in the previous exercise.

In [65]:
# plt.figure(figsize=(8, 3))
# dist_words.plot(20,cumulative = False)
# plt.show()

In [55]:
# filtered_words = [] # creates an empty list
# for word in tokenized_word:
#       if word not in stopwords.words():
#            filtered_words.append(word)

In [58]:
# dist_words_filter = FreqDist(filtered_words)
# print (dist_words_filter)

<FreqDist with 4575 samples and 16758 outcomes>

In [64]:
# dist_words_filter.most_common(50)

# Creating the NER object

In [5]:
# Download English module

!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ------ --------------------------------- 2.1/12.8 MB 10.1 MB/s eta 0:00:02
     ------------- -------------------------- 4.2/12.8 MB 10.2 MB/s eta 0:00:01
     --------------------- ------------------ 6.8/12.8 MB 10.9 MB/s eta 0:00:01
     --------------------------------- ----- 11.0/12.8 MB 13.2 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 12.9 MB/s  0:00:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [6]:
NER = spacy.load("en_core_web_sm")

In [7]:
book = NER(data)

In [84]:
# Visualize identified entities

displacy.render(book[273:1000], style = "ent", jupyter = True)

# Splitting the sentence entities from the NER object

In [9]:
df_sentences = [] # empty shell to store results

# Loop through sentences, get entity list for each sentence
for sent in book.sents:
    entity_list = [ent.text for ent in sent.ents]
    df_sentences.append({"sentence": sent, "entities": entity_list})
    
df_sentences = pd.DataFrame(df_sentences)

In [10]:
df_sentences.head(10)

,sentence,entities
0,"(Jump, to, content, Main, menu, Search, Donate...","[Main, Search Donate Create, Key, the 20th cen..."
1,"(The, World, Wars, sparked, tension, between, ...","[The World Wars, the Cold War, the World Wide ..."
2,"(These, advancements, have, played, a, signifi...","[the 21st century, today]"
3,"(Historic, events, in, the, 20th, century[edit...","[20th, 1914]"
4,"(The, new, beginning, of, the, 20th, century, ...",[the 20th century]
5,"(The, 1900s, saw, the, decade, herald, a, seri...","[The 1900s, the decade]"
6,"(1914, saw, the, completion, of, the, Panama, ...","[1914, the Panama Canal]"
7,"(The, scramble, for, Africa, continued, in, th...","[Africa, the 1900s]"
8,"(The, atrocities, in, the, Congo, Free, State,...",[the Congo Free State]
9,"(From, 1914, to, 1918, the, First, World, War,...","[1914 to 1918, the First World War]"

# Filtering the entities to get the countries

In [12]:
countries_list = pd.read_csv('countries_list_20th_century_1.5.csv')

In [13]:
cleaned_list = [row.strip() for row in countries_list['country_name']]

In [15]:
country_df = pd.DataFrame(cleaned_list, columns = ['country_name'])

In [18]:
country_df.head()

  country_name
0  Afghanistan
1      Albania
2      Algeria
3      Andorra
4       Angola

In [16]:
# Function to filter out entities not of interest

def filter_entity(ent_list, character_df):
    return [ent for ent in ent_list 
            if ent in list(country_df['country_name'])]

In [19]:
# Check

filter_entity(["Afghanistan", "CF", "2"], country_df)

['Afghanistan']

In [20]:
df_sentences['character_entities'] = df_sentences['entities'].apply(lambda x: filter_entity(x, country_df))

In [21]:
df_sentences['character_entities'].head(20)

0                    []
1                    []
2                    []
3                    []
4                    []
5                    []
6                    []
7                    []
8                    []
9                    []
10                   []
11                   []
12    [France, Austria]
13             [Russia]
14    [Germany, Russia]
15            [Germany]
16            [Germany]
17                   []
18                   []
19                   []
Name: character_entities, dtype: object

In [22]:
# Filter out sentences that don't have any character entities

df_sentences_filtered = df_sentences[df_sentences['character_entities'].map(len) > 0]

In [23]:
df_sentences_filtered.tail(10)

,sentence,entities,character_entities
1113,"("", The, forgotten, violence, that, helped, In...",[India],[India]
1118,"("", Indian, Independence, Day, :, everything, ...","[Indian Independence Day, Partition between In...",[Pakistan]
1127,"(^, "", The, Philippines, ,, 1898â€“1946, |, US...","[Philippines, 1898â€“1946, US House of Represe...",[Philippines]
1157,"("", Colonial, Cartographies, ,, Postcolonial, ...","[Colonial Cartographies, Postcolonial Borders,...",[Afghanistan]
1197,"(The, Moldovans, :, Romania, ,, Russia, ,, and...","[Moldovans, Romania, Russia, the Politics of C...","[Romania, Russia]"
1260,"("", Selling, ', Operation, Passage, to, Freedo...","[Thomas Dooley, the Religious Overtones of Ear...",[Vietnam]
1294,"("", Stuck, in, Endless, Preliminaries, :, Viet...","[Stuck in Endless Preliminaries, Vietnam, the ...",[Vietnam]
1567,"("", Anti, -, American, Behavior, in, the, Midd...","[Anti-American Behavior, the Middle East, a Fi...",[Lebanon]
1573,"(The, Rise, of, China, and, India, :, A, New, ...","[India, New Asian]",[India]
1574,"(Singapore, :, World, Scientific, ., doi:10.11...","[Singapore, World Scientific]",[Singapore]

# Creating the relationship dataframe

In [24]:
# Defining relationships 

# window size = 5 : this defines how many sentences will be looked at simultaneously 
relationships = [] # create an empty list

for i in range(df_sentences_filtered.index[-1]):
    end_i = min(i+5, df_sentences_filtered.index[-1])
    char_list = sum((df_sentences_filtered.loc[i: end_i].character_entities), [])
    
    # Remove duplicated characters that are next to each other
    char_unique = [char_list[i] for i in range(len(char_list)) 
                   if (i==0) or char_list[i] != char_list[i-1]]
    
    if len(char_unique) > 1:
        for idx, a in enumerate(char_unique[:-1]):
            b = char_unique[idx + 1]
            relationships.append({"source": a, "target": b})

In [25]:
relationship_df = pd.DataFrame(relationships)

In [26]:
relationship_df

      source     target
0     France    Austria
1     France    Austria
2    Austria     Russia
3     France    Austria
4    Austria     Russia
..       ...        ...
566    India  Singapore
567    India  Singapore
568    India  Singapore
569    India  Singapore
570    India  Singapore

[571 rows x 2 columns]

In [27]:
# Sort the cases with a->b and b->a

relationship_df = pd.DataFrame(np.sort(relationship_df.values, axis = 1), columns = relationship_df.columns)
relationship_df.head(5)

    source  target
0  Austria  France
1  Austria  France
2  Austria  Russia
3  Austria  France
4  Austria  Russia

In [28]:
# Summarize the interactions

relationship_df["value"] = 1
relationship_df = relationship_df.groupby(["source","target"], sort=False, as_index=False).sum()

In [30]:
relationship_df.head(10)

    source   target  value
0  Austria   France      6
1  Austria   Russia      5
2  Germany   Russia     21
3  Austria  Germany     13
4  Germany    Italy     25
5  Germany    Spain      2
6   France   Poland     15
7   France  Germany     17
8  Germany   Poland     23
9  Estonia  Germany      5

# Saving the relationship file

In [32]:
relationship_df.to_csv('country_relationship.csv', index= False)